### ISSUE TITLE
MountVolume.SetUp failed for volume "test" : invalid character '/' looking for beginning of value

### ISSUE THREAD

**Issue by Sifa91** [Azure/kubernetes-keyvault-flexvol#113]
**Describe the bug**
After a fresh installation I tried to add an keyvault-flexvolumet and got a failure. I also checked the /var/log/kv-driver.log and found that there is also an error documented. 
"ERROR: {"status": "Failure", "message": "validation failed, resourcegroup is empty"}"

**Steps To Reproduce**
Just do the steps which described in your readme.md

**Expected behavior**

**Key Vault FlexVolume version**
keyvault-flexvolume:v0.0.11

**Access mode: service principal or pod identity**
Service principal

**Kubernetes version**
v1.11.0+d4cacc0

**Additional context**

**Comment by dirien** [comment]
I can confirm this error also.

**Comment by aramase** [comment]
@Sifa91 @dirien I tried the steps from the readme with v0.0.11 and I can't recreate the error. The only time I can recreate the scenario is if I don't provide the resource group in the pod spec. Can you confirm the resource group is provided in the pod spec?

**Comment by Sifa91** [comment]
Problem solved. RPM JQ was missing. 
You can close the issue.
