### ISSUE TITLE
Question: Is the Flexvolume a ram disk?

### ISSUE THREAD

**Issue by johnlento** [Azure/kubernetes-keyvault-flexvol#152]
**Describe the request**
This is just a generic question but I can’t seem to tell if the Flex Volume is backed in tmpfs.  Could you confirm if the secrets in the volume are stored in non-persistent storage?

**Explain why Key Vault FlexVolume needs it**
No secrets on disk!
**Describe the solution you'd like**
Secrets in a RAM disk.

**Describe alternatives you've considered**

**Additional context**

**Comment by ritazh** [comment]
Good question @johnlento! And yes it is a tmpfs volume. https://github.com/Azure/kubernetes-keyvault-flexvol/blob/master/deployment/flexvol-installer/kv#L148

Hope this helps!
