### ISSUE TITLE
SSL with ISTIO

### ISSUE THREAD

**Issue by veligithub** [Azure/kubernetes-keyvault-flexvol#154]
**Describe the bug**
During the modification of the istio-ingressgateway: 

eployments.extensions "istio-ingressgateway" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(Deployment.spec.template.spec.volumes[3].flexVolume.secretRef): invalid type for io.k8s.api.core.v1.LocalObjectReference: got "string", expected "map"

**Steps To Reproduce**

**Expected behavior**

**Key Vault FlexVolume version**

**Access mode: service principal or pod identity**

**Kubernetes version**

**Additional context**

**Comment by veligithub** [comment]
It is coming during the insertion of : 
  - mountPath: /etc/istio/keyvault-certs
          name: keyvault-certs
          readOnly: true

and

      - name: keyvault-certs
        flexVolume:
          driver: "azure/kv"
          secretRef:
            kvcreds
          options:
            usepodidentity: "false"
            keyvaultname: "i have the name of my kv here"
            keyvaultobjectnames: "myprivatekey;mycertificate"
            keyvaultobjecttypes: "key;cert"
            tenantid: "000-0000-000xxx-00000000"

**Comment by aramase** [comment]
@veligithub this needs to be 
```
      secretRef:
        name: kvcreds
```

**Comment by veligithub** [comment]
I am sorry but based on the article https://github.com/Azure/kubernetes-keyvault-flexvol i am using :
      secretRef:
        name: kvcreds

nevertheless i have this error
