### ISSUE TITLE
Issue running in Minikube

### ISSUE THREAD

**Issue by trhumphries** [Azure/kubernetes-keyvault-flexvol#182]
Unable to attach or mount volumes: unmounted volumes=[kvconfig2 kvconfig1], unattached volumes=[kvconfig2 default-token-27tbn kvconfig1]: failed to get Plugin from volumeSpec for volume "kvconfig1" err=no volume plugin matched; failed to get Plugin from volumeSpec for volume "kvconfig2" err=no volume plugin matched

Setup LV Flexvolume in Minikube using service principal 

Volume should be mounted 

0.0.16

Service principle 

minikube 1.7.3

**Additional context**

**Comment by aramase** [comment]
@trhumphries While installing on `minikube` the target dir needs to be https://github.com/Azure/kubernetes-keyvault-flexvol/blob/master/deployment/kv-flexvol-installer.yaml#L47. Once you update `/etc/kubernetes/volumeplugins` to `/usr/libexec/kubernetes/kubelet-plugins/volume/exec`  in the manifest and deploy to minikube it should work. 

Can you please try that out?

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/kubernetes-keyvault-flexvol/issues/182#issuecomment-597323434. Please feel free reopen if the above comment doesn't resolve the issue.

**Comment by joymon** [comment]
Hi @aramase ,
I am getting the same error. Could you please help me with the path that needs to be used as I am using K8s on Docker Desktop Win 10 machine with WSL2 backend. 

May I use the same path below  suggested for minikube?
/usr/libexec/kubernetes/kubelet-plugins/volume/exec
