### ISSUE TITLE
Multiple secrets in one flexvolume

### ISSUE THREAD

**Issue by timja** [Azure/kubernetes-keyvault-flexvol#37]
Hi 

Would it be possible to have multiple secrets in one flexvolume?
I'm trying to integrate this with jenkins configuration as code plugin:
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/kubernetes-secrets

Which expects each secret to be under the same directory
i.e
```
/kvmnt/secret-1
/kvmnt/secret-2
```

To get more than one secret working with this tool it seems like you need different mount point per secret,
i.e.
```
/secret-1-mount/secret-1
/secret-2-mount/secret-2
```

Is it possible to do what I'm trying to achieve?

Thanks

**Comment by ritazh** [comment]
Thanks for the feedback @timja. Seems like a good feature to add.Will add this to our feature backlog to implement this in the next release. Will keep you posted!

**Comment by idanlevin** [comment]
+1 would love to have a list of secrets in one volume

**Comment by khenidak** [comment]
I just want to clarify. `One volume` == `One keyvault`. I think the idea of multiple objects in one volume is ok as long as it points to one `keyvault`

Please do keep in mind that the current model enables us to spit correct error for `access denied` because it is one object per vol. With the proposed model the error will be very confusing because the user will have to read through to know exactly which object failed.

**Comment by idanlevin** [comment]
@khenidak I agree that one volume should be assigned to one keyvault, however I disagree with your second comment, KeyVault doesn't manage access per keys, it can only give a "GET" access which automatically gives you access to all keys. 

Your comment is still valid for missing keys though, if a user accesses a key that doesn't exist, he will have to read through, but I believe it's worth it :)

**Comment by nphmuller** [comment]
We have some applications that require 5+ secrets. Definining a flex volume p. secret would get really verbose, really quick. So this would make a great feature for us.

**Comment by ThorstenHans** [comment]
I've the same situation as described by @nphmuller I thing almost every real world application has to deal with more than one secret / key / certificate for a single application component. 

I'd love to be able to pull all required items at once from a key vault instance to a single volume. 

As mentioned by @khenidak a single volume should only support items from a single keyvault

**Comment by ritazh** [comment]
Closed via https://github.com/Azure/kubernetes-keyvault-flexvol/pull/49
