### ISSUE TITLE
Leaking access tokens in log files

### ISSUE THREAD

**Issue by pjbgf** [Azure/kubernetes-keyvault-flexvol#42]
Currently the generated access tokens used to access KeyVault are being logged in plain-text. 

This allows a "reader" of the log files to privilege escalate, spoofing the Managed Identity in question and also gain access to sensitive information. Other identities could also be spoofed, depending on the credentials stored in the keyVault instance. 

Please consider the PR #41 I have just submitted in order to redact most of that information from the logs.

**Comment by ritazh** [comment]
closed via #41
