### ISSUE TITLE
Remove "list" permissions

### ISSUE THREAD

**Issue by idanlevin** [Azure/kubernetes-keyvault-flexvol#44]
Hi,

Does the FlexVol really needs a "list" permissions on KV?

Since KV doesn't have per-key-permissions, it's considered a best to only have a "get" permission without a "list" one, to avoid key traversing.

Assuming the user always provide a key name in the volume mount, I assume the "list" part is unnecessary.

Idan

**Comment by ritazh** [comment]
Good catch @idanlevin thanks for the issue!
