### ISSUE TITLE
Allow for different certificate format (public/private key)

### ISSUE THREAD

**Issue by serbrech** [Azure/kubernetes-keyvault-flexvol#50]
When pulling an object of type cert from keyvault, we do not have a choice in the format of the resulting file. Additionally, the current implementation only gets the public portion of the certificate.

Being able to pull both the public and secret part of the certificate in a `mycert.crt` and `mycert.key` would be useful to setup SSL endpoint for ingress controllers for example.

**Comment by hugree** [comment]
I think that I just hit that wall too. I uploaded a PFX certificate and it's not working with my Spring Boot application using it. When I use it directly it works fine. When I use it via the mounted flexvolume it's not working correctly. The file size is different. The mounted version is much smaller.

Is there any reason for such behavior?

**Comment by serbrech** [comment]
Try setting the type as secret.
The private part of the certificate is downloadable as a secret.
The « cert » type only downloads the public part of the cert.

**Comment by alexsandro-xpt** [comment]
So... alright.

**Comment by ritazh** [comment]
Fixed via #59
