### ISSUE TITLE
Allow to specify an Alias for the file name

### ISSUE THREAD

**Issue by serbrech** [Azure/kubernetes-keyvault-flexvol#51]
In the original [docs/Concept.md](https://github.com/Azure/kubernetes-keyvault-flexvol/blob/master/docs/concept.md) there is an optional `Alias` parameter, which is not implemented, but would indeed be useful.

Note that this would needs to consider multiple secret compatibility https://github.com/Azure/kubernetes-keyvault-flexvol/pull/49

**Comment by khenidak** [comment]
also #66 is related here.
